[book]
title       = "aaai ドキュメント"
authors     = ["nabbisen"]
language    = "ja"
src         = "src"

[output.html]
default-theme           = "light"
preferred-dark-theme    = "navy"
git-repository-url      = "https://github.com/nabbisen/aaai/tree/main/docs/src"
edit-url-template       = "https://github.com/nabbisen/aaai/edit/main/docs/src/{path}"
git-repository-icon     = "fa-github"
